[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Prototipo Practica Final"
authors = [{name = "Iris Alarcon", email = "iris.alarconp@gmail.com"}]
dynamic = ["version", "description"]
